CREATE TABLE ai_model_call_log (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    run_id VARCHAR(36) NOT NULL,
    trace_id VARCHAR(128),
    model_name VARCHAR(128) NOT NULL,
    provider_url VARCHAR(512) NOT NULL,
    status VARCHAR(32) NOT NULL,
    http_status INT,
    duration_millis BIGINT,
    input_tokens INT NOT NULL DEFAULT 0,
    output_tokens INT NOT NULL DEFAULT 0,
    safe_request_summary LONGTEXT,
    safe_response_summary LONGTEXT,
    error_type VARCHAR(128),
    safe_error_detail VARCHAR(2000),
    create_time DATETIME(3) NOT NULL,
    update_time DATETIME(3) NOT NULL,
    INDEX idx_model_call_run (run_id),
    INDEX idx_model_call_trace (trace_id),
    INDEX idx_model_call_created (create_time),
    INDEX idx_model_call_tenant_user (tenant_id, user_id)
);
